pushing updated ansible files for security review

diff --git a/bin/activate b/bin/activate
--- a/bin/activate
+++ b/bin/activate
@@ -14,13 +14,13 @@ fi
 
 source ./env.local
 if [ "$ANSIBLE_USER" = "" ]; then
-  echo 'ERROR: Please set your remote username using `echo ANSIBLE_USER=myuser > env.local`'
-  return 
+  echo 'ERROR: Please set your remote username using `echo ANSIBLE_USER=myuser >> env.local`'
+  return
 fi
 
 if [ "$AWS_SSH_KEY_ID" = "" ]; then
-  echo 'ERROR: Please set the name of an SSH key configured in your AWS user security credentials as described in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html using `echo AWS_SSH_KEY_ID=keyname > env.local`'
-  return 
+  echo 'ERROR: Please set the name of an SSH key configured in your AWS user security credentials as described in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html using `echo AWS_SSH_KEY_ID=keyname >> env.local`'
+  return
 fi
 
 source ./env.list
@@ -29,7 +29,18 @@ if grep -Fq "[${AWS_PROFILE}]" ~/.aws/credentials; then
 else
   echo "ERROR: Credentials for AWS profile ${AWS_PROFILE} not found in ~/.aws/credentials."
   echo "Please add credentials running \"aws configure --profile ${AWS_PROFILE}\" or by following instructions at http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles"
-  return 
+  return
+fi
+
+lpass -v &> /dev/null
+if [ $? == 0 ]; then
+  ANSIBLE_BECOME_PASS=$(lpass show --password "ssh-${AWS_PROFILE}")
+  ANSIBLE_VAULT_PASSWORD=$(lpass show --password "ansible-${AWS_PROFILE}")
+fi
+# TODO
+if [ "$ANSIBLE_BECOME_PASS" == "" ]; then
+  echo 'ERROR: Please create a lastpass password with the name 'ssh-${AWS_PROFILE}' and ensure you have the 'ansible-${AWS_PROFILE}' vault password'
+  return
 fi
 
 [ "$(alias | grep deactivate)" ] && deactivate  # In case already activated.
@@ -45,21 +56,33 @@ fi
 
 echo "Building Ansible/AWSCLI container (this may take some time)"
 docker build -q -t ansible .docker/ansible
-CONTAINER="docker run -it --rm -e "ANSIBLE_NOCOLOR=$ANSIBLE_NOCOLOR" -e "ANSIBLE_BECOME_PASS=$ANSIBLE_BECOME_PASS"  -e "ANSIBLE_HOST_KEY_CHECKING=$ANSIBLE_HOST_KEY_CHECKING" --env-file ./env.list --env-file ./env.local -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -v $HOME/.aws/credentials:/root/.aws/credentials -v $PWD:/opt/ansible ansible"
+CONTAINER="docker run -it --rm "\
+" -e 'ANSIBLE_BECOME_PASS=$ANSIBLE_BECOME_PASS'"\
+" -e 'ANSIBLE_VAULT_PASSWORD=$ANSIBLE_VAULT_PASSWORD'"\
+" -e 'ANSIBLE_HOST_KEY_CHECKING=$ANSIBLE_HOST_KEY_CHECKING'"\
+" --env-file ./env.list --env-file ./env.local"\
+" -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent"\
+" -v $HOME/.ssh/known_hosts:/root/.ssh/known_hosts"\
+" -e SSH_AUTH_SOCK=/ssh-agent"\
+" -v $HOME/.aws/credentials:/root/.aws/credentials"\
+" -v $PWD:/opt/ansible ansible"
 INVENTORY="-i inventory"
+BECOME="-u $ANSIBLE_USER -e ansible_become_pass=\"\$ANSIBLE_BECOME_PASS\""
+VAULT="--vault-password-file=/opt/ansible/bin/vault-password"
 
 # Aliases to run in container.
-alias ansible="${CONTAINER} ansible -u $ANSIBLE_USER ${INVENTORY}"
+alias ansible="${CONTAINER} ansible ${VAULT} ${BECOME} ${INVENTORY}"
 alias ansible-lint="${CONTAINER} ansible-lint"
-alias ansible-console="${CONTAINER} ansible-console  -u $ANSIBLE_USER ${INVENTORY}"
+alias ansible-console="${CONTAINER} ansible-console ${VAULT} ${BECOME} ${INVENTORY}"
 alias ansible-shell="${CONTAINER} bash"
-alias ansible-playbook="${CONTAINER} ansible-playbook -u $ANSIBLE_USER ${INVENTORY}"
-alias ansible-vault="${CONTAINER} ansible-vault"
+alias ansible-playbook="${CONTAINER} ansible-playbook ${VAULT} ${BECOME} ${INVENTORY}"
+alias ansible-vault="${CONTAINER} ansible-vault ${VAULT}"
 alias ansible-galaxy="${CONTAINER} ansible-galaxy"
 alias aws="${CONTAINER} aws"
 alias inventory="${CONTAINER} inventory/ec2.py --list"
 alias mkpasswd="${CONTAINER} python -c 'from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())'"
 
-# Remove and reinstall Ansible Galaxy roles, to ensure latest version.
-ansible-shell -c 'rm -rf /opt/ansible/roles/*'
-ansible-galaxy install -r requirements.yml
+# Install Ansible Galaxy roles
+${CONTAINER} ansible-galaxy install -r requirements.yml
+${CONTAINER} chown -R $UID roles
+
